version: '2'
services:
  db:
    image: postgres
    volumes_from:
      - pg_data

  web:
    environment:
      - DATABASE_HOST=db
      - DEBUG=false
    image: kordetech/korde.no:latest
    ports:
      - "8000:80"
    links:
      - db
  migration:
    environment:
      - DATABASE_HOST=db
    image: kordetech/korde.no:latest
    command: python manage.py migrate
  pg_data:
    image: kordetech/pg_data